### PR TITLE
Remove `daikon.Runtime` class

### PR DESCRIPTION
**Pull request by mernst**
We don't know what it is for, and it does not seem to be used.

### CODE REVIEW

**Comment by markro49** [comment]
What about daikon/java/daikon/test/split/targets/fuzzy.spinfo?  Seems to reference daikon.Runtime.ps_count

**Comment by mernst** [comment]
I don't know what the fuzzy.spinfo file is.  It doesn't seem to be used. :-(

**Review by markro49 — APPROVED** [review]

**Comment by markro49** [comment]
This pull request obsoletes 348?

**Comment by mernst** [comment]
> This pull request obsoletes #348?

Yes, it does.  It was inspired by your comment on #348.

**Pull request merged**
