### PR TITLE
Update todo.txt

### PR DESCRIPTION
**Pull request by rarworld**
Added my initials to the "--exception switch "-Task

### CODE REVIEW

**Comment by mernst** [comment]
Have you been able to make any progress on this task? Do you need help with anything?

**Comment by rarworld** [comment]
I'm almost finish. Exception-Handling can be switched. I just have to make some testing. I will commit it soon

**Comment by mernst** [comment]
Excellent!  I'm glad to hear it and look forward to your contribution.

**Comment by mernst** [comment]
Closed in favor of #56

**Pull request closed without merging**
