### PR TITLE
Refactorings for Java 11 support

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by mernst** [comment]
@markro49 The point of assigning this pull request to you is to verify that this does not move code outside the try block that, for some subtle reason, needs to be within the try block.

**Comment by markro49** [comment]
getClassLoader can throw a SecurityException.  I don't know if this is an issue or not.  It could be that if the user program under analysis installs a security manager then the DynComp instrumenter may have problems anyway,  I don't have enough knowledge in this area to answer the question.

**Comment by mernst** [comment]
So, it sounds from your answer like we should close this pull request without merging the change, because there is an important side effect that must happen within the scope of the try block.
Is that right?

**Comment by markro49** [comment]
Code as is might catch SecurityException and throw RuntimeException ("Unexpected error loading Instrument", e). (Where e is SecurityException.)  In same circumstances, the revised code would just throw the SecurityException.  I think I'm OK with that - your call.  I do like your code simplification.  It's just a question of inside or side the try/catch.

**Pull request merged**
